platform :ios, '9.0'

def network
    pod 'Starscream'
    pod 'JSONRPCKit'
    pod 'Moya'
    pod 'Alamofire'
    pod 'Kingfisher'
end

def data
    pod 'ObjectMapper'
end

def resource
    pod 'R.swift'
end

def architecture
   pod 'ReSwift'
   pod 'LocalizationKit'
   pod 'SwiftTheme'

end

def permission
    pod 'Proposer'
end

def extension
    pod 'EZSwiftExtensions', :git => 'https://github.com/Steven-Cheung/EZSwiftExtensions', :branch => 'swift4'
end

def ui
    pod 'TinyConstraints'
    pod 'ESTabBarController-swift'
    pod 'KMNavigationBarTransition'
    pod 'NVActivityIndicatorView'
    pod 'DGElasticPullToRefresh' , :git => 'https://github.com/sammygutierrez/DGElasticPullToRefresh'
    pod 'BeareadToast', :git => 'https://github.com/phpmaple/BeareadToast'
end

def other
    pod 'Siren'
end

target 'cybexMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Reveal-SDK', :configurations => ['Debug']

  network
  data
  resource
  architecture
  permission
  extension
  ui
  other
  
  # Pods for cybexMobile
  target 'cybexMobileTests' do
    inherit! :search_paths
    # Pods for testing
#    pod 'Quick'
#    pod 'Nimble'
#    pod 'OHHTTPStubs'
  end

end

target 'cybexMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cybexMobile-tvOS

  target 'cybexMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


